var ActionTypes = {
    RESET: 'RESET',

    LOAD_APPLICANTS: 'LOAD_APPLICANTS',

    ADD_GIFT: 'ADD_GIFT',
    DELETE_GIFT: 'DELETE_GIFT',

    INITIALIZE_LOTTERY: 'INITIALIZE_LOTTERY',
    START_LOTTERY: 'START_LOTTERY',
    SET_WINNER: 'SET_WINNER'
};

module.exports = ActionTypes;
